# Generated by Django 4.0.4 on 2022-06-20 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0004_rename_neighborhood_business_neighbourhood_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updates',
            old_name='display',
            new_name='displayer',
        ),
    ]
